// <auto-generated />
namespace IntegrationWS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class agregando_tabla_notificacion_pedido_espera : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregando_tabla_notificacion_pedido_espera));
        
        string IMigrationMetadata.Id
        {
            get { return "202103232015191_agregando_tabla_notificacion_pedido_espera"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
