// <auto-generated />
namespace IntegrationWS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class agregando_tabla_producto_de_contrato : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregando_tabla_producto_de_contrato));
        
        string IMigrationMetadata.Id
        {
            get { return "202101121228049_agregando_tabla_producto_de_contrato"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
