//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationWS.WSMovilDGII {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPlacaResult", Namespace="http://dgii.gov.do/")]
    [System.SerializableAttribute()]
    public partial class GetPlacaResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntegrationWS.WSMovilDGII.PlacaModel placaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntegrationWS.WSMovilDGII.OposicionModel[] oposicionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public IntegrationWS.WSMovilDGII.PlacaModel placa {
            get {
                return this.placaField;
            }
            set {
                if ((object.ReferenceEquals(this.placaField, value) != true)) {
                    this.placaField = value;
                    this.RaisePropertyChanged("placa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public IntegrationWS.WSMovilDGII.OposicionModel[] oposiciones {
            get {
                return this.oposicionesField;
            }
            set {
                if ((object.ReferenceEquals(this.oposicionesField, value) != true)) {
                    this.oposicionesField = value;
                    this.RaisePropertyChanged("oposiciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlacaModel", Namespace="http://dgii.gov.do/")]
    [System.SerializableAttribute()]
    public partial class PlacaModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MARCA_VEHICULOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MODELO_VEHICULOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COLORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ANO_FABRICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PLACAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RNC_CEDULA_PROPIETARIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MARCA_VEHICULO {
            get {
                return this.MARCA_VEHICULOField;
            }
            set {
                if ((object.ReferenceEquals(this.MARCA_VEHICULOField, value) != true)) {
                    this.MARCA_VEHICULOField = value;
                    this.RaisePropertyChanged("MARCA_VEHICULO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MODELO_VEHICULO {
            get {
                return this.MODELO_VEHICULOField;
            }
            set {
                if ((object.ReferenceEquals(this.MODELO_VEHICULOField, value) != true)) {
                    this.MODELO_VEHICULOField = value;
                    this.RaisePropertyChanged("MODELO_VEHICULO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string COLOR {
            get {
                return this.COLORField;
            }
            set {
                if ((object.ReferenceEquals(this.COLORField, value) != true)) {
                    this.COLORField = value;
                    this.RaisePropertyChanged("COLOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ANO_FABRICACION {
            get {
                return this.ANO_FABRICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.ANO_FABRICACIONField, value) != true)) {
                    this.ANO_FABRICACIONField = value;
                    this.RaisePropertyChanged("ANO_FABRICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PLACA {
            get {
                return this.PLACAField;
            }
            set {
                if ((object.ReferenceEquals(this.PLACAField, value) != true)) {
                    this.PLACAField = value;
                    this.RaisePropertyChanged("PLACA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOField, value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RNC_CEDULA_PROPIETARIO {
            get {
                return this.RNC_CEDULA_PROPIETARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.RNC_CEDULA_PROPIETARIOField, value) != true)) {
                    this.RNC_CEDULA_PROPIETARIOField = value;
                    this.RaisePropertyChanged("RNC_CEDULA_PROPIETARIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OposicionModel", Namespace="http://dgii.gov.do/")]
    [System.SerializableAttribute()]
    public partial class OposicionModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long NUMERO_OPOSICIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_OPOSICIONField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long NUMERO_OPOSICION {
            get {
                return this.NUMERO_OPOSICIONField;
            }
            set {
                if ((this.NUMERO_OPOSICIONField.Equals(value) != true)) {
                    this.NUMERO_OPOSICIONField = value;
                    this.RaisePropertyChanged("NUMERO_OPOSICION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TIPO_OPOSICION {
            get {
                return this.TIPO_OPOSICIONField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_OPOSICIONField, value) != true)) {
                    this.TIPO_OPOSICIONField = value;
                    this.RaisePropertyChanged("TIPO_OPOSICION");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSolicitudResult", Namespace="http://dgii.gov.do/")]
    [System.SerializableAttribute()]
    public partial class GetSolicitudResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntegrationWS.WSMovilDGII.SolicitudModel solicitudField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public IntegrationWS.WSMovilDGII.SolicitudModel solicitud {
            get {
                return this.solicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.solicitudField, value) != true)) {
                    this.solicitudField = value;
                    this.RaisePropertyChanged("solicitud");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudModel", Namespace="http://dgii.gov.do/")]
    [System.SerializableAttribute()]
    public partial class SolicitudModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string canalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tramiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string numeroSolicitud {
            get {
                return this.numeroSolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroSolicitudField, value) != true)) {
                    this.numeroSolicitudField = value;
                    this.RaisePropertyChanged("numeroSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                if ((object.ReferenceEquals(this.canalField, value) != true)) {
                    this.canalField = value;
                    this.RaisePropertyChanged("canal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tramite {
            get {
                return this.tramiteField;
            }
            set {
                if ((object.ReferenceEquals(this.tramiteField, value) != true)) {
                    this.tramiteField = value;
                    this.RaisePropertyChanged("tramite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaField, value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string estatus {
            get {
                return this.estatusField;
            }
            set {
                if ((object.ReferenceEquals(this.estatusField, value) != true)) {
                    this.estatusField = value;
                    this.RaisePropertyChanged("estatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dgii.gov.do/", ConfigurationName="WSMovilDGII.WSMovilDGIISoap")]
    public interface WSMovilDGIISoap {
        
        // CODEGEN: Generating message contract since element name value from namespace http://dgii.gov.do/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetContribuyentes", ReplyAction="*")]
        IntegrationWS.WSMovilDGII.GetContribuyentesResponse GetContribuyentes(IntegrationWS.WSMovilDGII.GetContribuyentesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetContribuyentes", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetContribuyentesResponse> GetContribuyentesAsync(IntegrationWS.WSMovilDGII.GetContribuyentesRequest request);
        
        // CODEGEN: Generating message contract since element name value from namespace http://dgii.gov.do/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetContribuyentesCount", ReplyAction="*")]
        IntegrationWS.WSMovilDGII.GetContribuyentesCountResponse GetContribuyentesCount(IntegrationWS.WSMovilDGII.GetContribuyentesCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetContribuyentesCount", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetContribuyentesCountResponse> GetContribuyentesCountAsync(IntegrationWS.WSMovilDGII.GetContribuyentesCountRequest request);
        
        // CODEGEN: Generating message contract since element name codigoBusqueda from namespace http://dgii.gov.do/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetDocumento", ReplyAction="*")]
        IntegrationWS.WSMovilDGII.GetDocumentoResponse GetDocumento(IntegrationWS.WSMovilDGII.GetDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetDocumento", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetDocumentoResponse> GetDocumentoAsync(IntegrationWS.WSMovilDGII.GetDocumentoRequest request);
        
        // CODEGEN: Generating message contract since element name value from namespace http://dgii.gov.do/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetVehiculoPorDATAMATRIX", ReplyAction="*")]
        IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXResponse GetVehiculoPorDATAMATRIX(IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetVehiculoPorDATAMATRIX", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXResponse> GetVehiculoPorDATAMATRIXAsync(IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXRequest request);
        
        // CODEGEN: Generating message contract since element name RNC from namespace http://dgii.gov.do/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetNCF", ReplyAction="*")]
        IntegrationWS.WSMovilDGII.GetNCFResponse GetNCF(IntegrationWS.WSMovilDGII.GetNCFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetNCF", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetNCFResponse> GetNCFAsync(IntegrationWS.WSMovilDGII.GetNCFRequest request);
        
        // CODEGEN: Generating message contract since element name RNC from namespace http://dgii.gov.do/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetNCF2", ReplyAction="*")]
        IntegrationWS.WSMovilDGII.GetNCF2Response GetNCF2(IntegrationWS.WSMovilDGII.GetNCF2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetNCF2", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetNCF2Response> GetNCF2Async(IntegrationWS.WSMovilDGII.GetNCF2Request request);
        
        // CODEGEN: Generating message contract since element name RNC from namespace http://dgii.gov.do/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetPlaca", ReplyAction="*")]
        IntegrationWS.WSMovilDGII.GetPlacaResponse GetPlaca(IntegrationWS.WSMovilDGII.GetPlacaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetPlaca", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetPlacaResponse> GetPlacaAsync(IntegrationWS.WSMovilDGII.GetPlacaRequest request);
        
        // CODEGEN: Generating message contract since element name RNC from namespace http://dgii.gov.do/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetSolicitud", ReplyAction="*")]
        IntegrationWS.WSMovilDGII.GetSolicitudResponse GetSolicitud(IntegrationWS.WSMovilDGII.GetSolicitudRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dgii.gov.do/GetSolicitud", ReplyAction="*")]
        System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetSolicitudResponse> GetSolicitudAsync(IntegrationWS.WSMovilDGII.GetSolicitudRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContribuyentesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContribuyentes", Namespace="http://dgii.gov.do/", Order=0)]
        public IntegrationWS.WSMovilDGII.GetContribuyentesRequestBody Body;
        
        public GetContribuyentesRequest() {
        }
        
        public GetContribuyentesRequest(IntegrationWS.WSMovilDGII.GetContribuyentesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetContribuyentesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string value;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int patronBusqueda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int inicioFilas;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int filaFilas;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IMEI;
        
        public GetContribuyentesRequestBody() {
        }
        
        public GetContribuyentesRequestBody(string value, int patronBusqueda, int inicioFilas, int filaFilas, string IMEI) {
            this.value = value;
            this.patronBusqueda = patronBusqueda;
            this.inicioFilas = inicioFilas;
            this.filaFilas = filaFilas;
            this.IMEI = IMEI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContribuyentesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContribuyentesResponse", Namespace="http://dgii.gov.do/", Order=0)]
        public IntegrationWS.WSMovilDGII.GetContribuyentesResponseBody Body;
        
        public GetContribuyentesResponse() {
        }
        
        public GetContribuyentesResponse(IntegrationWS.WSMovilDGII.GetContribuyentesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetContribuyentesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetContribuyentesResult;
        
        public GetContribuyentesResponseBody() {
        }
        
        public GetContribuyentesResponseBody(string GetContribuyentesResult) {
            this.GetContribuyentesResult = GetContribuyentesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContribuyentesCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContribuyentesCount", Namespace="http://dgii.gov.do/", Order=0)]
        public IntegrationWS.WSMovilDGII.GetContribuyentesCountRequestBody Body;
        
        public GetContribuyentesCountRequest() {
        }
        
        public GetContribuyentesCountRequest(IntegrationWS.WSMovilDGII.GetContribuyentesCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetContribuyentesCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string value;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IMEI;
        
        public GetContribuyentesCountRequestBody() {
        }
        
        public GetContribuyentesCountRequestBody(string value, string IMEI) {
            this.value = value;
            this.IMEI = IMEI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContribuyentesCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContribuyentesCountResponse", Namespace="http://dgii.gov.do/", Order=0)]
        public IntegrationWS.WSMovilDGII.GetContribuyentesCountResponseBody Body;
        
        public GetContribuyentesCountResponse() {
        }
        
        public GetContribuyentesCountResponse(IntegrationWS.WSMovilDGII.GetContribuyentesCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetContribuyentesCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetContribuyentesCountResult;
        
        public GetContribuyentesCountResponseBody() {
        }
        
        public GetContribuyentesCountResponseBody(string GetContribuyentesCountResult) {
            this.GetContribuyentesCountResult = GetContribuyentesCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumento", Namespace="http://dgii.gov.do/", Order=0)]
        public IntegrationWS.WSMovilDGII.GetDocumentoRequestBody Body;
        
        public GetDocumentoRequest() {
        }
        
        public GetDocumentoRequest(IntegrationWS.WSMovilDGII.GetDocumentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetDocumentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codigoBusqueda;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int patronBusqueda;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IMEI;
        
        public GetDocumentoRequestBody() {
        }
        
        public GetDocumentoRequestBody(string codigoBusqueda, int patronBusqueda, string IMEI) {
            this.codigoBusqueda = codigoBusqueda;
            this.patronBusqueda = patronBusqueda;
            this.IMEI = IMEI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDocumentoResponse", Namespace="http://dgii.gov.do/", Order=0)]
        public IntegrationWS.WSMovilDGII.GetDocumentoResponseBody Body;
        
        public GetDocumentoResponse() {
        }
        
        public GetDocumentoResponse(IntegrationWS.WSMovilDGII.GetDocumentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetDocumentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDocumentoResult;
        
        public GetDocumentoResponseBody() {
        }
        
        public GetDocumentoResponseBody(string GetDocumentoResult) {
            this.GetDocumentoResult = GetDocumentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVehiculoPorDATAMATRIXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVehiculoPorDATAMATRIX", Namespace="http://dgii.gov.do/", Order=0)]
        public IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXRequestBody Body;
        
        public GetVehiculoPorDATAMATRIXRequest() {
        }
        
        public GetVehiculoPorDATAMATRIXRequest(IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetVehiculoPorDATAMATRIXRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string value;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IMEI;
        
        public GetVehiculoPorDATAMATRIXRequestBody() {
        }
        
        public GetVehiculoPorDATAMATRIXRequestBody(string value, string IMEI) {
            this.value = value;
            this.IMEI = IMEI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVehiculoPorDATAMATRIXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVehiculoPorDATAMATRIXResponse", Namespace="http://dgii.gov.do/", Order=0)]
        public IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXResponseBody Body;
        
        public GetVehiculoPorDATAMATRIXResponse() {
        }
        
        public GetVehiculoPorDATAMATRIXResponse(IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetVehiculoPorDATAMATRIXResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetVehiculoPorDATAMATRIXResult;
        
        public GetVehiculoPorDATAMATRIXResponseBody() {
        }
        
        public GetVehiculoPorDATAMATRIXResponseBody(string GetVehiculoPorDATAMATRIXResult) {
            this.GetVehiculoPorDATAMATRIXResult = GetVehiculoPorDATAMATRIXResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNCFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNCF", Namespace="http://dgii.gov.do/", Order=0)]
        public IntegrationWS.WSMovilDGII.GetNCFRequestBody Body;
        
        public GetNCFRequest() {
        }
        
        public GetNCFRequest(IntegrationWS.WSMovilDGII.GetNCFRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetNCFRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RNC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NCF;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IMEI;
        
        public GetNCFRequestBody() {
        }
        
        public GetNCFRequestBody(string RNC, string NCF, string IMEI) {
            this.RNC = RNC;
            this.NCF = NCF;
            this.IMEI = IMEI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNCFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNCFResponse", Namespace="http://dgii.gov.do/", Order=0)]
        public IntegrationWS.WSMovilDGII.GetNCFResponseBody Body;
        
        public GetNCFResponse() {
        }
        
        public GetNCFResponse(IntegrationWS.WSMovilDGII.GetNCFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetNCFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNCFResult;
        
        public GetNCFResponseBody() {
        }
        
        public GetNCFResponseBody(string GetNCFResult) {
            this.GetNCFResult = GetNCFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNCF2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNCF2", Namespace="http://dgii.gov.do/", Order=0)]
        public IntegrationWS.WSMovilDGII.GetNCF2RequestBody Body;
        
        public GetNCF2Request() {
        }
        
        public GetNCF2Request(IntegrationWS.WSMovilDGII.GetNCF2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetNCF2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RNC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NCF;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string rncComprador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string codSeguridad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IMEI;
        
        public GetNCF2RequestBody() {
        }
        
        public GetNCF2RequestBody(string RNC, string NCF, string rncComprador, string codSeguridad, string IMEI) {
            this.RNC = RNC;
            this.NCF = NCF;
            this.rncComprador = rncComprador;
            this.codSeguridad = codSeguridad;
            this.IMEI = IMEI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNCF2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNCF2Response", Namespace="http://dgii.gov.do/", Order=0)]
        public IntegrationWS.WSMovilDGII.GetNCF2ResponseBody Body;
        
        public GetNCF2Response() {
        }
        
        public GetNCF2Response(IntegrationWS.WSMovilDGII.GetNCF2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetNCF2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNCF2Result;
        
        public GetNCF2ResponseBody() {
        }
        
        public GetNCF2ResponseBody(string GetNCF2Result) {
            this.GetNCF2Result = GetNCF2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlacaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlaca", Namespace="http://dgii.gov.do/", Order=0)]
        public IntegrationWS.WSMovilDGII.GetPlacaRequestBody Body;
        
        public GetPlacaRequest() {
        }
        
        public GetPlacaRequest(IntegrationWS.WSMovilDGII.GetPlacaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetPlacaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RNC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Placa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IMEI;
        
        public GetPlacaRequestBody() {
        }
        
        public GetPlacaRequestBody(string RNC, string Placa, string IMEI) {
            this.RNC = RNC;
            this.Placa = Placa;
            this.IMEI = IMEI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlacaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlacaResponse", Namespace="http://dgii.gov.do/", Order=0)]
        public IntegrationWS.WSMovilDGII.GetPlacaResponseBody Body;
        
        public GetPlacaResponse() {
        }
        
        public GetPlacaResponse(IntegrationWS.WSMovilDGII.GetPlacaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetPlacaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IntegrationWS.WSMovilDGII.GetPlacaResult GetPlacaResult;
        
        public GetPlacaResponseBody() {
        }
        
        public GetPlacaResponseBody(IntegrationWS.WSMovilDGII.GetPlacaResult GetPlacaResult) {
            this.GetPlacaResult = GetPlacaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSolicitudRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSolicitud", Namespace="http://dgii.gov.do/", Order=0)]
        public IntegrationWS.WSMovilDGII.GetSolicitudRequestBody Body;
        
        public GetSolicitudRequest() {
        }
        
        public GetSolicitudRequest(IntegrationWS.WSMovilDGII.GetSolicitudRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetSolicitudRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RNC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string solicitud;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IMEI;
        
        public GetSolicitudRequestBody() {
        }
        
        public GetSolicitudRequestBody(string RNC, string solicitud, string IMEI) {
            this.RNC = RNC;
            this.solicitud = solicitud;
            this.IMEI = IMEI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSolicitudResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSolicitudResponse", Namespace="http://dgii.gov.do/", Order=0)]
        public IntegrationWS.WSMovilDGII.GetSolicitudResponseBody Body;
        
        public GetSolicitudResponse() {
        }
        
        public GetSolicitudResponse(IntegrationWS.WSMovilDGII.GetSolicitudResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dgii.gov.do/")]
    public partial class GetSolicitudResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IntegrationWS.WSMovilDGII.GetSolicitudResult GetSolicitudResult;
        
        public GetSolicitudResponseBody() {
        }
        
        public GetSolicitudResponseBody(IntegrationWS.WSMovilDGII.GetSolicitudResult GetSolicitudResult) {
            this.GetSolicitudResult = GetSolicitudResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSMovilDGIISoapChannel : IntegrationWS.WSMovilDGII.WSMovilDGIISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSMovilDGIISoapClient : System.ServiceModel.ClientBase<IntegrationWS.WSMovilDGII.WSMovilDGIISoap>, IntegrationWS.WSMovilDGII.WSMovilDGIISoap {
        
        public WSMovilDGIISoapClient() {
        }
        
        public WSMovilDGIISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSMovilDGIISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSMovilDGIISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSMovilDGIISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegrationWS.WSMovilDGII.GetContribuyentesResponse IntegrationWS.WSMovilDGII.WSMovilDGIISoap.GetContribuyentes(IntegrationWS.WSMovilDGII.GetContribuyentesRequest request) {
            return base.Channel.GetContribuyentes(request);
        }
        
        public string GetContribuyentes(string value, int patronBusqueda, int inicioFilas, int filaFilas, string IMEI) {
            IntegrationWS.WSMovilDGII.GetContribuyentesRequest inValue = new IntegrationWS.WSMovilDGII.GetContribuyentesRequest();
            inValue.Body = new IntegrationWS.WSMovilDGII.GetContribuyentesRequestBody();
            inValue.Body.value = value;
            inValue.Body.patronBusqueda = patronBusqueda;
            inValue.Body.inicioFilas = inicioFilas;
            inValue.Body.filaFilas = filaFilas;
            inValue.Body.IMEI = IMEI;
            IntegrationWS.WSMovilDGII.GetContribuyentesResponse retVal = ((IntegrationWS.WSMovilDGII.WSMovilDGIISoap)(this)).GetContribuyentes(inValue);
            return retVal.Body.GetContribuyentesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetContribuyentesResponse> IntegrationWS.WSMovilDGII.WSMovilDGIISoap.GetContribuyentesAsync(IntegrationWS.WSMovilDGII.GetContribuyentesRequest request) {
            return base.Channel.GetContribuyentesAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetContribuyentesResponse> GetContribuyentesAsync(string value, int patronBusqueda, int inicioFilas, int filaFilas, string IMEI) {
            IntegrationWS.WSMovilDGII.GetContribuyentesRequest inValue = new IntegrationWS.WSMovilDGII.GetContribuyentesRequest();
            inValue.Body = new IntegrationWS.WSMovilDGII.GetContribuyentesRequestBody();
            inValue.Body.value = value;
            inValue.Body.patronBusqueda = patronBusqueda;
            inValue.Body.inicioFilas = inicioFilas;
            inValue.Body.filaFilas = filaFilas;
            inValue.Body.IMEI = IMEI;
            return ((IntegrationWS.WSMovilDGII.WSMovilDGIISoap)(this)).GetContribuyentesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegrationWS.WSMovilDGII.GetContribuyentesCountResponse IntegrationWS.WSMovilDGII.WSMovilDGIISoap.GetContribuyentesCount(IntegrationWS.WSMovilDGII.GetContribuyentesCountRequest request) {
            return base.Channel.GetContribuyentesCount(request);
        }
        
        public string GetContribuyentesCount(string value, string IMEI) {
            IntegrationWS.WSMovilDGII.GetContribuyentesCountRequest inValue = new IntegrationWS.WSMovilDGII.GetContribuyentesCountRequest();
            inValue.Body = new IntegrationWS.WSMovilDGII.GetContribuyentesCountRequestBody();
            inValue.Body.value = value;
            inValue.Body.IMEI = IMEI;
            IntegrationWS.WSMovilDGII.GetContribuyentesCountResponse retVal = ((IntegrationWS.WSMovilDGII.WSMovilDGIISoap)(this)).GetContribuyentesCount(inValue);
            return retVal.Body.GetContribuyentesCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetContribuyentesCountResponse> IntegrationWS.WSMovilDGII.WSMovilDGIISoap.GetContribuyentesCountAsync(IntegrationWS.WSMovilDGII.GetContribuyentesCountRequest request) {
            return base.Channel.GetContribuyentesCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetContribuyentesCountResponse> GetContribuyentesCountAsync(string value, string IMEI) {
            IntegrationWS.WSMovilDGII.GetContribuyentesCountRequest inValue = new IntegrationWS.WSMovilDGII.GetContribuyentesCountRequest();
            inValue.Body = new IntegrationWS.WSMovilDGII.GetContribuyentesCountRequestBody();
            inValue.Body.value = value;
            inValue.Body.IMEI = IMEI;
            return ((IntegrationWS.WSMovilDGII.WSMovilDGIISoap)(this)).GetContribuyentesCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegrationWS.WSMovilDGII.GetDocumentoResponse IntegrationWS.WSMovilDGII.WSMovilDGIISoap.GetDocumento(IntegrationWS.WSMovilDGII.GetDocumentoRequest request) {
            return base.Channel.GetDocumento(request);
        }
        
        public string GetDocumento(string codigoBusqueda, int patronBusqueda, string IMEI) {
            IntegrationWS.WSMovilDGII.GetDocumentoRequest inValue = new IntegrationWS.WSMovilDGII.GetDocumentoRequest();
            inValue.Body = new IntegrationWS.WSMovilDGII.GetDocumentoRequestBody();
            inValue.Body.codigoBusqueda = codigoBusqueda;
            inValue.Body.patronBusqueda = patronBusqueda;
            inValue.Body.IMEI = IMEI;
            IntegrationWS.WSMovilDGII.GetDocumentoResponse retVal = ((IntegrationWS.WSMovilDGII.WSMovilDGIISoap)(this)).GetDocumento(inValue);
            return retVal.Body.GetDocumentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetDocumentoResponse> IntegrationWS.WSMovilDGII.WSMovilDGIISoap.GetDocumentoAsync(IntegrationWS.WSMovilDGII.GetDocumentoRequest request) {
            return base.Channel.GetDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetDocumentoResponse> GetDocumentoAsync(string codigoBusqueda, int patronBusqueda, string IMEI) {
            IntegrationWS.WSMovilDGII.GetDocumentoRequest inValue = new IntegrationWS.WSMovilDGII.GetDocumentoRequest();
            inValue.Body = new IntegrationWS.WSMovilDGII.GetDocumentoRequestBody();
            inValue.Body.codigoBusqueda = codigoBusqueda;
            inValue.Body.patronBusqueda = patronBusqueda;
            inValue.Body.IMEI = IMEI;
            return ((IntegrationWS.WSMovilDGII.WSMovilDGIISoap)(this)).GetDocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXResponse IntegrationWS.WSMovilDGII.WSMovilDGIISoap.GetVehiculoPorDATAMATRIX(IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXRequest request) {
            return base.Channel.GetVehiculoPorDATAMATRIX(request);
        }
        
        public string GetVehiculoPorDATAMATRIX(string value, string IMEI) {
            IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXRequest inValue = new IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXRequest();
            inValue.Body = new IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXRequestBody();
            inValue.Body.value = value;
            inValue.Body.IMEI = IMEI;
            IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXResponse retVal = ((IntegrationWS.WSMovilDGII.WSMovilDGIISoap)(this)).GetVehiculoPorDATAMATRIX(inValue);
            return retVal.Body.GetVehiculoPorDATAMATRIXResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXResponse> IntegrationWS.WSMovilDGII.WSMovilDGIISoap.GetVehiculoPorDATAMATRIXAsync(IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXRequest request) {
            return base.Channel.GetVehiculoPorDATAMATRIXAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXResponse> GetVehiculoPorDATAMATRIXAsync(string value, string IMEI) {
            IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXRequest inValue = new IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXRequest();
            inValue.Body = new IntegrationWS.WSMovilDGII.GetVehiculoPorDATAMATRIXRequestBody();
            inValue.Body.value = value;
            inValue.Body.IMEI = IMEI;
            return ((IntegrationWS.WSMovilDGII.WSMovilDGIISoap)(this)).GetVehiculoPorDATAMATRIXAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegrationWS.WSMovilDGII.GetNCFResponse IntegrationWS.WSMovilDGII.WSMovilDGIISoap.GetNCF(IntegrationWS.WSMovilDGII.GetNCFRequest request) {
            return base.Channel.GetNCF(request);
        }
        
        public string GetNCF(string RNC, string NCF, string IMEI) {
            IntegrationWS.WSMovilDGII.GetNCFRequest inValue = new IntegrationWS.WSMovilDGII.GetNCFRequest();
            inValue.Body = new IntegrationWS.WSMovilDGII.GetNCFRequestBody();
            inValue.Body.RNC = RNC;
            inValue.Body.NCF = NCF;
            inValue.Body.IMEI = IMEI;
            IntegrationWS.WSMovilDGII.GetNCFResponse retVal = ((IntegrationWS.WSMovilDGII.WSMovilDGIISoap)(this)).GetNCF(inValue);
            return retVal.Body.GetNCFResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetNCFResponse> IntegrationWS.WSMovilDGII.WSMovilDGIISoap.GetNCFAsync(IntegrationWS.WSMovilDGII.GetNCFRequest request) {
            return base.Channel.GetNCFAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetNCFResponse> GetNCFAsync(string RNC, string NCF, string IMEI) {
            IntegrationWS.WSMovilDGII.GetNCFRequest inValue = new IntegrationWS.WSMovilDGII.GetNCFRequest();
            inValue.Body = new IntegrationWS.WSMovilDGII.GetNCFRequestBody();
            inValue.Body.RNC = RNC;
            inValue.Body.NCF = NCF;
            inValue.Body.IMEI = IMEI;
            return ((IntegrationWS.WSMovilDGII.WSMovilDGIISoap)(this)).GetNCFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegrationWS.WSMovilDGII.GetNCF2Response IntegrationWS.WSMovilDGII.WSMovilDGIISoap.GetNCF2(IntegrationWS.WSMovilDGII.GetNCF2Request request) {
            return base.Channel.GetNCF2(request);
        }
        
        public string GetNCF2(string RNC, string NCF, string rncComprador, string codSeguridad, string IMEI) {
            IntegrationWS.WSMovilDGII.GetNCF2Request inValue = new IntegrationWS.WSMovilDGII.GetNCF2Request();
            inValue.Body = new IntegrationWS.WSMovilDGII.GetNCF2RequestBody();
            inValue.Body.RNC = RNC;
            inValue.Body.NCF = NCF;
            inValue.Body.rncComprador = rncComprador;
            inValue.Body.codSeguridad = codSeguridad;
            inValue.Body.IMEI = IMEI;
            IntegrationWS.WSMovilDGII.GetNCF2Response retVal = ((IntegrationWS.WSMovilDGII.WSMovilDGIISoap)(this)).GetNCF2(inValue);
            return retVal.Body.GetNCF2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetNCF2Response> IntegrationWS.WSMovilDGII.WSMovilDGIISoap.GetNCF2Async(IntegrationWS.WSMovilDGII.GetNCF2Request request) {
            return base.Channel.GetNCF2Async(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetNCF2Response> GetNCF2Async(string RNC, string NCF, string rncComprador, string codSeguridad, string IMEI) {
            IntegrationWS.WSMovilDGII.GetNCF2Request inValue = new IntegrationWS.WSMovilDGII.GetNCF2Request();
            inValue.Body = new IntegrationWS.WSMovilDGII.GetNCF2RequestBody();
            inValue.Body.RNC = RNC;
            inValue.Body.NCF = NCF;
            inValue.Body.rncComprador = rncComprador;
            inValue.Body.codSeguridad = codSeguridad;
            inValue.Body.IMEI = IMEI;
            return ((IntegrationWS.WSMovilDGII.WSMovilDGIISoap)(this)).GetNCF2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegrationWS.WSMovilDGII.GetPlacaResponse IntegrationWS.WSMovilDGII.WSMovilDGIISoap.GetPlaca(IntegrationWS.WSMovilDGII.GetPlacaRequest request) {
            return base.Channel.GetPlaca(request);
        }
        
        public IntegrationWS.WSMovilDGII.GetPlacaResult GetPlaca(string RNC, string Placa, string IMEI) {
            IntegrationWS.WSMovilDGII.GetPlacaRequest inValue = new IntegrationWS.WSMovilDGII.GetPlacaRequest();
            inValue.Body = new IntegrationWS.WSMovilDGII.GetPlacaRequestBody();
            inValue.Body.RNC = RNC;
            inValue.Body.Placa = Placa;
            inValue.Body.IMEI = IMEI;
            IntegrationWS.WSMovilDGII.GetPlacaResponse retVal = ((IntegrationWS.WSMovilDGII.WSMovilDGIISoap)(this)).GetPlaca(inValue);
            return retVal.Body.GetPlacaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetPlacaResponse> IntegrationWS.WSMovilDGII.WSMovilDGIISoap.GetPlacaAsync(IntegrationWS.WSMovilDGII.GetPlacaRequest request) {
            return base.Channel.GetPlacaAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetPlacaResponse> GetPlacaAsync(string RNC, string Placa, string IMEI) {
            IntegrationWS.WSMovilDGII.GetPlacaRequest inValue = new IntegrationWS.WSMovilDGII.GetPlacaRequest();
            inValue.Body = new IntegrationWS.WSMovilDGII.GetPlacaRequestBody();
            inValue.Body.RNC = RNC;
            inValue.Body.Placa = Placa;
            inValue.Body.IMEI = IMEI;
            return ((IntegrationWS.WSMovilDGII.WSMovilDGIISoap)(this)).GetPlacaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IntegrationWS.WSMovilDGII.GetSolicitudResponse IntegrationWS.WSMovilDGII.WSMovilDGIISoap.GetSolicitud(IntegrationWS.WSMovilDGII.GetSolicitudRequest request) {
            return base.Channel.GetSolicitud(request);
        }
        
        public IntegrationWS.WSMovilDGII.GetSolicitudResult GetSolicitud(string RNC, string solicitud, string IMEI) {
            IntegrationWS.WSMovilDGII.GetSolicitudRequest inValue = new IntegrationWS.WSMovilDGII.GetSolicitudRequest();
            inValue.Body = new IntegrationWS.WSMovilDGII.GetSolicitudRequestBody();
            inValue.Body.RNC = RNC;
            inValue.Body.solicitud = solicitud;
            inValue.Body.IMEI = IMEI;
            IntegrationWS.WSMovilDGII.GetSolicitudResponse retVal = ((IntegrationWS.WSMovilDGII.WSMovilDGIISoap)(this)).GetSolicitud(inValue);
            return retVal.Body.GetSolicitudResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetSolicitudResponse> IntegrationWS.WSMovilDGII.WSMovilDGIISoap.GetSolicitudAsync(IntegrationWS.WSMovilDGII.GetSolicitudRequest request) {
            return base.Channel.GetSolicitudAsync(request);
        }
        
        public System.Threading.Tasks.Task<IntegrationWS.WSMovilDGII.GetSolicitudResponse> GetSolicitudAsync(string RNC, string solicitud, string IMEI) {
            IntegrationWS.WSMovilDGII.GetSolicitudRequest inValue = new IntegrationWS.WSMovilDGII.GetSolicitudRequest();
            inValue.Body = new IntegrationWS.WSMovilDGII.GetSolicitudRequestBody();
            inValue.Body.RNC = RNC;
            inValue.Body.solicitud = solicitud;
            inValue.Body.IMEI = IMEI;
            return ((IntegrationWS.WSMovilDGII.WSMovilDGIISoap)(this)).GetSolicitudAsync(inValue);
        }
    }
}
